# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc997113808fd203f668ae01a3cf394f305d27cb0bb0c84490432ed1e1ae90c911a0df3a815bdd1cbb82c0da943de4790399ec0fbe112b33a0719701f53d9d9f

test:
  secret_key_base: 1463f40396a9f85bdee93a9af37b3ad3a63b74ef0162a5a358a2ec6c8299233dfbeae9b9aa28c012cb33d23625a018f6b25b3de50bc95b799bf3fcc87560ecc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 3cfc3ef85ba34a1d7935df5f311b9c7b3e8049b2d52ebee515fb717801b95c83035dab63f27b04f04facbcea6912408c33564769144737c36f885d3fab54b6b4
